#pragma once

// Auto-generated by generate_shims.py

#include "lvlens_registry.h"
#include <lvgl.h>

// 1) Undefine alias macros
#ifdef lv_obj_create
#undef lv_obj_create
#endif
#ifdef lv_label_create
#undef lv_label_create
#endif
#ifdef lv_button_create
#undef lv_button_create
#endif
#ifdef lv_dropdown_create
#undef lv_dropdown_create
#endif
#ifdef lv_img_create
#undef lv_img_create
#endif

// 2) Raw helpers and hook wrappers for real functions
static inline lv_obj_t *lvlens_lv_obj_create_raw(lv_obj_t *parent) {
    return lv_obj_create(parent);
}

static inline lv_obj_t *lvlens_lv_obj_create(lv_obj_t *parent, const char *file, int line) {
    lv_obj_t *obj = lvlens_lv_obj_create_raw(parent);
    lvlens_register(obj, file, line, "lv_obj_create");
    return obj;
}

static inline lv_obj_t *lvlens_lv_label_create_raw(lv_obj_t *parent) {
    return lv_label_create(parent);
}

static inline lv_obj_t *lvlens_lv_label_create(lv_obj_t *parent, const char *file, int line) {
    lv_obj_t *obj = lvlens_lv_label_create_raw(parent);
    lvlens_register(obj, file, line, "lv_label_create");
    return obj;
}

static inline lv_obj_t *lvlens_lv_button_create_raw(lv_obj_t *parent) {
    return lv_button_create(parent);
}

static inline lv_obj_t *lvlens_lv_button_create(lv_obj_t *parent, const char *file, int line) {
    lv_obj_t *obj = lvlens_lv_button_create_raw(parent);
    lvlens_register(obj, file, line, "lv_button_create");
    return obj;
}

static inline lv_obj_t *lvlens_lv_dropdown_create_raw(lv_obj_t *parent) {
    return lv_dropdown_create(parent);
}

static inline lv_obj_t *lvlens_lv_dropdown_create(lv_obj_t *parent, const char *file, int line) {
    lv_obj_t *obj = lvlens_lv_dropdown_create_raw(parent);
    lvlens_register(obj, file, line, "lv_dropdown_create");
    return obj;
}

static inline lv_obj_t *lvlens_lv_image_create_raw(lv_obj_t *parent) {
    return lv_image_create(parent);
}

static inline lv_obj_t *lvlens_lv_image_create(lv_obj_t *parent, const char *file, int line) {
    lv_obj_t *obj = lvlens_lv_image_create_raw(parent);
    lvlens_register(obj, file, line, "lv_img_create");
    return obj;
}

// 3) Redirect both real and alias names
#define lv_obj_create(parent) \
    lvlens_lv_obj_create((parent), __FILE__, __LINE__)

#define lv_label_create(parent) \
    lvlens_lv_label_create((parent), __FILE__, __LINE__)

#define lv_button_create(parent) \
    lvlens_lv_button_create((parent), __FILE__, __LINE__)

#define lv_dropdown_create(parent) \
    lvlens_lv_dropdown_create((parent), __FILE__, __LINE__)

#define lv_image_create(parent) \
    lvlens_lv_image_create((parent), __FILE__, __LINE__)

#define lv_img_create(parent) \
    lvlens_lv_image_create((parent), __FILE__, __LINE__)
