[package]
name = "stratum-ui-common"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.71.1"
toml = "0.8.22"

[dependencies]
lazy_static = "1.5.0"
log = "0.4.26"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]
